### ISSUE TITLE
Python 3.7 compatibility

### ISSUE THREAD

**Issue by andgineer** [toumorokoshi/flask-transmute#9]
It does work with python 3.6 but does not work with 3.7

```
$ python3.7 app.py

Traceback (most recent call last):
  File "app.py", line 1, in <module>
    import flask_transmute
  File "/home/anso/.local/lib/python3.7/site-packages/flask_transmute/__init__.py", line 1, in <module>
    from transmute_core import *
  File "/home/anso/.local/lib/python3.7/site-packages/transmute_core/__init__.py", line 1, in <module>
    from .decorators import describe, annotate
  File "/home/anso/.local/lib/python3.7/site-packages/transmute_core/decorators.py", line 2, in <module>
    from .function import TransmuteAttributes
  File "/home/anso/.local/lib/python3.7/site-packages/transmute_core/function/__init__.py", line 4, in <module>
    from .transmute_function import TransmuteFunction
  File "/home/anso/.local/lib/python3.7/site-packages/transmute_core/function/transmute_function.py", line 4, in <module>
    from ..context import default_context
  File "/home/anso/.local/lib/python3.7/site-packages/transmute_core/context.py", line 1, in <module>
    from .object_serializers import get_default_object_serializer_set
  File "/home/anso/.local/lib/python3.7/site-packages/transmute_core/object_serializers/__init__.py", line 2, in <module>
    from .cattrs_serializer import CattrsSerializer
  File "/home/anso/.local/lib/python3.7/site-packages/transmute_core/object_serializers/cattrs_serializer/__init__.py", line 3, in <module>
    from .converter import create_cattrs_converter
  File "/home/anso/.local/lib/python3.7/site-packages/transmute_core/object_serializers/cattrs_serializer/converter.py", line 2, in <module>
    from cattr import Converter
  File "/home/anso/.local/lib/python3.7/site-packages/cattr/__init__.py", line 2, in <module>
    from .converters import Converter, UnstructureStrategy
  File "/home/anso/.local/lib/python3.7/site-packages/cattr/converters.py", line 2, in <module>
    from typing import (List, Mapping, Sequence, Optional, MutableSequence,
ImportError: cannot import name '_Union' from 'typing' (/usr/lib/python3.7/typing.py)

```

**Comment by andgineer** [comment]
If I install catt 0.9.1 it at least import the module and starts with Python 3.7.
I am not sure if it would be working without problems.

transmute-core 1.9.1 has requirement cattrs<=0.6.0,>=0.5.0

**Comment by andgineer** [comment]
so we have to use new cattr in core 
and use here new version of transmute core

**Comment by toumorokoshi** [comment]
Hi! Unfortunately cattrs has made significant interface changes in 0.6.0, so it requires a bit of refactoring to re-implement the custom serialization that was added.

I'll see if I can take another stab at it in the next couple of days, which should help unblock 3.7

**Comment by toumorokoshi** [comment]
there is a new release 1.9.2 that addressed this. Tested with py3.7 and it brings up an example server. Thanks!
